### PR TITLE
added screenshots in readme.md

### PR DESCRIPTION
**Pull request by SRIMANKS**
added 3 screenshots in readme.md file
image
image
image

### CODE REVIEW

**Comment by adamsyy** [comment]
can you change the first 2 screenshots

**Comment by SRIMANKS** [comment]
How do you prefer i can change

**Comment by adamsyy** [comment]
takee better ss of first 2, not sure how to explain

**Comment by SRIMANKS** [comment]
i updated the screenshot check once and merge

**Pull request merged**
